Use the actually documented defaults in the cloudscale_server resource
cloudscale-ch/terraform-provider-cloudscale pull request #1
Opened 2018-03-08 16:44 UTC by davidhalter

If using use_private_network = False or use_ipv6 = False the default was still
always true, because we checked it with ResourceData.GetOk, which only returns
ok if the value is non-zero. One possible fix in the future would have been to
use ResourceData.GetOkExists instead. However this method only exists on the
master branch and not in any current terraform release. Therefore we are just
using defaults and ResourceData.Get.

Added a test to avoid the issue in the future.

I'm not a go programmer so please let me know if there are issues in here.

2018-03-08 16:53 UTC, davidhalter commented
I have also a related issue: If I pass a complex list (`interfaces` in my case) to terraform, only the first item is listed when using `terraform show`. Was there a bug in terraform with lists that contain maps that contains lists etc.?

I struggle to find a solution there, because at the point where the plugin hands off the content to terraform, the content has two elements and in `terraform show` there's just one element.

2018-03-09 13:44 UTC, davidhalter commented
Ok. So there's now two changes:

1. Fixed a bug around private networks not working (added a default)
2. Fixed a bug where when using computed sets, not all items might be shown when using `terraform show`.

Both of them have tests. Please tell me if you need to know more.

2018-03-09 22:13 UTC, catsby requested changes
Hey David!

`GetOkExists` was added in Terraform 0.10.1 (August 15, 2017). The version of Terraform's `helper/schema` library vendored into this Provider repository is from July 2017. If you updated your Terraform dependency, you'd get that method!

I noticed there are some changes here from `TypeList` to `TypeSet`, can you elaborate on why that is? `TypeSet` is used for collection items that have no specific ordering, and `TypeList` is for items that need to have their order preserved. Is that the case here?

2018-03-10 12:10 UTC, davidhalter commented
HI Clint

I guess there's always an ordering. That's at least what the cloudscale.ch API gives me. Of course we can get rid of the ordering, but I actually see an advantage in the ordering of computed attribute.

I'm happy to just revert that last commit where three attributes were changed from TypeSet to TypeList. I just did that, because I found it cleaner in general. Your call. The other 2 TypeSet -> TypeList changes are IMO necessary, because the set somehow removed some items from the final terraform show output (also they are definitely sorted).

I tried to update terraform like this: govendor fetch github.com/hashicorp/terraform@v0.11.3, but with this I got a few hundred new packages into my source tree. Is there a way how I can just upgrade the necessary parts? Sorry `go` newbie here.

2018-03-12 22:02 UTC, catsby commented
>but I actually see an advantage in the ordering of computed attribute.
What advantages would those be?

`TypeList` should be used for things that ordering has relevance, e.g. rules or policies that need to be interpreted or considered in the order they are given. 

With`TypeSet` for those attributes, we have no guarantee the ordering that they are presented in the configuration will match what is sent to the API after the first initial create, because when these items are read back from the API and saved to state, their key is a hash of their values, and they are stored in alphanumeric order on that key. So long as those items hash to that key, the ordering is irrelevant to Terraform.

With `TypeList` , these items are stored in state in increasing numeric order based on the order they are given when set. 

>The other 2 TypeSet -> TypeList changes are IMO necessary, because the set somehow removed some items from the final terraform show output

I assume this is your `2)` point above? I would be interested in knowing more, that doesn't sound like correct behavior. 

>The other 2 TypeSet -> TypeList changes are IMO necessary, because the set somehow removed some items from the final terraform show output (also they are definitely sorted).

Volumes and interfaces? Network interfaces sound ordered certainly. Volumes I'm not 100% sure, but I'll defer to you there 😄 

I'll work on getting you the right command for `govendor`, it's not always straight forward :/

2018-03-13 17:48 UTC, davidhalter commented
> Volumes and interfaces? Network interfaces sound ordered certainly. Volumes I'm not 100% sure, but I'll defer to you there

Then I guess we'll keep the order. The reason for ordering volumes is `/dev/sda` `/dev/sdb`, etc. They are ordered in that order. The network ports are also ordered (eth0, eth1, etc).

> I'll work on getting you the right command for govendor, it's not always straight forward :/

That would be great! I really tried for a long time and couldn't get it to work.

> I assume this is your 2) point above? I would be interested in knowing more, that doesn't sound like correct behavior.

I guess I can only explain it with the test. If you add `use_private_network = True`, terraform won't listen all network interfaces. By simply switching to TypeList it's working. Running the test in https://github.com/terraform-providers/terraform-provider-cloudscale/pull/1/commits/70aa51577b43ffe2c573ee99f152566911787d77 without the other changes will fail. I suspect that something is wrong with the comparison of objects within sets. But I really don't even have enough knowledge of how you even work with sets in go to file a bug report.

2018-03-23 17:43 UTC, davidhalter commented
@catsby If it's too much work for you, we can just use it as it is.

2018-04-03 09:26 UTC, davidhalter commented
Can anybody from HashiCorp please look at this?

2018-04-03 21:35 UTC, catsby commented
Hey @davidhalter -

I opened https://github.com/terraform-providers/terraform-provider-cloudscale/pull/2 to update the dependencies. I believe that is good to merge, then you can rebase this PR from `master` and use `GetOkExists`

2018-04-05 11:56 UTC, davidhalter commented
Hi Clint

I have rebased  on master (based on your commits) and I'm using GetOkExists now. The changes are therefore pretty minimal.

The tests are passing. Hope it is ready to merge, now.

~ Dave

2018-04-05 15:17 UTC, catsby approved these changes
Thanks! 

```
Running..

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run=TestAccCloudscaleServer_PrivateNetwork -timeout 120m
?       github.com/terraform-providers/terraform-provider-cloudscale    [no test files]
=== RUN   TestAccCloudscaleServer_PrivateNetwork
--- PASS: TestAccCloudscaleServer_PrivateNetwork (45.01s)
PASS
ok      github.com/terraform-providers/terraform-provider-cloudscale/cloudscale 45.036s
```

2018-04-05 15:18 UTC, merged

2018-04-05 15:38 UTC, davidhalter commented
@catsby I don't really understand the terraform release cycles. Is there a defined release date for this commit?

2018-04-05 15:50 UTC, catsby commented
@davidhalter release cadence varies by activity in the Provider. The AWS Provider is likely our most active provider, and has a releases about every 2 weeks. 

The last release of the CloudScale provider was in November of 2017. This pull request is the only activity since. We could release a new version, if you'd like.

- [ ]

2018-04-05 19:44 UTC, davidhalter commented
@catsby It's not like there's going to be a lot of changes in the next few weeks. I'd be happy if we released a new one.

2018-04-06 20:15 UTC, catsby commented
v1.0.1 is out

2018-04-07 10:06 UTC, davidhalter commented
Thanks a lot dude!